const GET_CARTS = "GET_CARTS"
const SET_CARTS = "SET_CARTS"
const INCREASE_CARTS = "INCREASE_CARTS"
const DECREASE_CARTS = "DECREASE_CARTS"
const DELETE_CARTS = "DELETE_CARTS"
const COLOR_CARTS = "COLOR_CARTS"
const SIZE_CARTS = "SIZE_CARTS"


export {
    GET_CARTS , SET_CARTS , DELETE_CARTS , DECREASE_CARTS , INCREASE_CARTS , COLOR_CARTS , SIZE_CARTS
}