const GET_ORDERS = "GET_ORDERS"
const GET_ORDER = "GET_ORDER"
const SET_ORDERS = "SET_ORDERS"
const INCREASE_ORDERS = "INCREASE_ORDERS"
const DECREASE_ORDERS = "DECREASE_ORDERS"
const DELETE_ORDERS = "DELETE_ORDERS"


export {
    GET_ORDERS , GET_ORDER , SET_ORDERS , DELETE_ORDERS , DECREASE_ORDERS , INCREASE_ORDERS 
}