const GET_PRODUCTS = "GET_PRODUCTS" ;
const GET_SINGLE_PRODUCTS = "GET_SINGLE_PRODUCTS" ;
const GET_TABS_PRODUCTS = "GET_TABS_PRODUCTS" ;
const SET_PRODUCT_ID = "SET_PRODUCT_ID" ;
const GET_PRODUCTS_FILTER = "GET_PRODUCTS_FILTER" ;
const GET_CATYONE = "GET_CATYONE" ;
const GET_CATYTWO = "GET_CATYTWO" ;
const GET_CATIGORIES = "GET_CATIGORIES" ;
const GET_COUNT = "GET_COUNT" ;
const GET_COLORS = "GET_COLORS" ;
const GET_SIZES = "GET_SIZES" ;
const GET_FEATURE_PRODUCTS = "GET_FEATURE_PRODUCTS" ;
const GET_LIMITED_PRODUCTS = "GET_LIMITED_PRODUCTS" ;
const GET_EXTRA_PRODUCTS = "GET_EXTRA_PRODUCTS" ;
const GET_SIMILER_PRODUCTS = "GET_SIMILER_PRODUCTS" ;
const GET_RANDOM_PRODUCT = "GET_RANDOM_PRODUCT" ;


export {
    GET_PRODUCTS , GET_SINGLE_PRODUCTS , GET_TABS_PRODUCTS  , SET_PRODUCT_ID , GET_PRODUCTS_FILTER , GET_CATYONE , 
    GET_CATYTWO , GET_SIZES , GET_COLORS , GET_COUNT , GET_CATIGORIES , GET_FEATURE_PRODUCTS , GET_LIMITED_PRODUCTS ,
    GET_EXTRA_PRODUCTS , GET_SIMILER_PRODUCTS , GET_RANDOM_PRODUCT 
}